ROTATE_DEFAULT = 0
ZOOM_DEFAULT = 0
FLIP_OPTIONS = ['None', 'X', 'Y', 'Both']
BLUR_DEFAULT = 0
CONTRAST_DEFAULT = 0
EFFECT_OPTIONS = ['None', 'Emboss', 'Find Edges', 'Contour', 'Edge Enhance']
BRIGHTNESS_DEFAULT = 1
VIBRANCE_DEFAULT = 1
GREYSCALE_DEFAULT = False
INVERT_DEFAULT = False

BACKGROUND_COLOUR = '#242424'
WHITE = '#ffffff'
GREY = 'grey'
BLUE = '#1f6aa5'
DARK_GREY = '#4a4a4a'
CLOSE_ORANGE = "#355F9B"
SLIDER_BG = '#64686b'

DROPDOWN_MAIN_COLOUR = '#444'
DROPDOWN_HOVER_COLOUR = '#333'
DROPDOWN_MENU_COLOUR = '#666'